# Site settings
title: Alex Campbell
email: alexander.campbell@colorado.edu
description: ""
baseurl: ""
url: "http://Zandrr.github.io"
twitter_username: CampbellAlexS
github_username:  Zandrr

# Build settings
markdown: kramdown
permalink: pretty
