# Site settings
title: Alex Campbell
email: campbellalex11@gmail.com
description: ""
baseurl: ""
url: "http://alexcampbell.co"
twitter_username: itsalexcampbell
github_username:  Zandrr

# Build settings
markdown: kramdown
permalink: pretty

